name: Hello World
author: ducnm-github
description: Some descriptions
inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: ducnm-git
outputs:
  time:
    description: "The greeting time"
runs:
  using: "node12"
  main: "dist/index.js"
